import {
  all_apparel_list,
  all_item_list,
  all_jewelry_list,
  all_weapon_list,
  armor_traits,
  craftables,
  falseString,
  jewelry_traits,
  styled_items,
  styles,
  traits,
  weapon_traits,
} from "./models";

export const STYLED_ITEMS: styled_items[] = [
  "axes",
  "belts",
  "boots",
  "bows",
  "chests",
  "daggers",
  "gloves",
  "helmets",
  "legs",
  "maces",
  "shields",
  "shoulders",
  "staves",
  "swords",
];

export const ALL_APPAREL_LIST: all_apparel_list[] = [
  "Shield",
  "Robe",
  "Shirt",
  "Shoes",
  "Gloves",
  "Hat",
  "Breeches",
  "Epaulets",
  "Sash",
  "Jack",
  "Boots",
  "Bracers",
  "Helmet",
  "Guards",
  "Arm Cops",
  "Belt",
  "Curaiss",
  "Sabatons",
  "Gauntlets",
  "Helm",
  "Greaves",
  "Pauldron",
  "Girdle",
];

export const ALL_WEAPON_LIST: all_weapon_list[] = [
  "Axe",
  "Mace",
  "Sword",
  "Battle Axe",
  "Maul",
  "Greatsword",
  "Dagger",
  "Bow",
  "Inferno Staff",
  "Ice Staff",
  "Lightning Staff",
  "Restoration Staff",
];

export const ALL_JEWLERY_LIST: all_jewelry_list[] = ["Necklace", "Ring"];

export const ALL_CRAFTABLES_LIST: all_item_list[] = [
  "Axe",
  "Mace",
  "Sword",
  "Battle Axe",
  "Maul",
  "Greatsword",
  "Dagger",
  "Bow",
  "Inferno Staff",
  "Ice Staff",
  "Lightning Staff",
  "Restoration Staff",
  "Shield",
  "Robe",
  "Shirt",
  "Shoes",
  "Gloves",
  "Hat",
  "Breeches",
  "Epaulets",
  "Sash",
  "Jack",
  "Boots",
  "Bracers",
  "Helmet",
  "Guards",
  "Arm Cops",
  "Belt",
  "Curaiss",
  "Sabatons",
  "Gauntlets",
  "Helm",
  "Greaves",
  "Pauldron",
  "Girdle",
  "Necklace",
  "Ring",
];

export const CRAFTABLES: craftables = {
  WEAPON: ALL_WEAPON_LIST,
  ARMOR: ALL_APPAREL_LIST,
  JEWELRY: ALL_JEWLERY_LIST,
};

export const FALSE10: falseString[] = ["false", "false", "false", "false", "false", "false", "false", "false", "false", "false"];

export const WEAPON_TRAITS: weapon_traits[] = [
  "Powered",
  "Charged",
  "Precise",
  "Infused",
  "Defending",
  "Training",
  "Sharpened",
  "Decisive",
  "Nirnhoned",
];

export const ARMOR_TRAITS: armor_traits[] = [
  "Sturdy",
  "Impenetrable",
  "Reinforced",
  "Wellfitted",
  "Training",
  "Infused",
  "Invigorating",
  "Divines",
  "Nirnhoned",
];

export const JEWELRY_TRAITS: jewelry_traits[] = [
  "Healthy",
  "Arcane",
  "Robust",
  "Bloodthirsty",
  "Harmony",
  "Infused",
  "Triune",
  "Protective",
  "Swift",
];

export const TRAITS: traits = {
  WEAPON_TRAITS,
  ARMOR_TRAITS,
  JEWELRY_TRAITS,
};

export const STYLES: styles[] = [
  "High Elf",
  "Dark Elf",
  "Wood Elf",
  "Nord",
  "Breton",
  "Redguard",
  "Khajiit",
  "Orcish",
  "Argonian",
  "Imperial",
  "Ancient Elf",
  "Barbaric",
  "Primal",
  "Daedric",
  "Dwemer",
  "Glass",
  "Xivkyn",
  "Akaviri",
  "Mercenary",
  "Yokudan",
  "Ancient Orc",
  "Trinimac",
  "Malacath",
  "Outlaw",
  "Aldmeri Dominion",
  "Daggerfall Covenant",
  "Ebonheart Pact",
  "Ra Gada",
  "SoulShriven",
  "Morag Tong",
  "Skinchanger",
  "Abahs Watch",
  "Thieves Guild",
  "Assassins League",
  "DromAthra",
  "Dark Brotherhood",
  "Ebony",
  "Draugr",
  "Minotaur",
  "Order of the Hour",
  "Celestial",
  "Hollowjack",
  "Grim Harlequin",
  "Silken Ring",
  "Mazzatun",
  "Stalhrim Frostcaster",
  "Buoyant Armiger",
  "Ashlander",
  "Militant Ordinator",
  "Telvanni",
  "Hlaalu",
  "Redoran",
  "Tsaesci",
  "Bloodforge",
  "Dreadhorn",
  "Apostle",
  "Ebonshadow",
  "Fang Lair",
  "Scalecaller",
  "Worm Cult",
  "Psijic",
  "Sapiarch",
  "Dremora",
  "Pyandonean",
  "Huntsman",
  "Silver Dawn",
  "Welkynar",
  "Honor Guard",
  "DeadWater",
  "Elder Argonian",
  "Coldsnap",
  "Meridian",
  "Anequina",
  "Pellitine",
  "Sunspire",
  "Dragonguard",
  "Stags of Zen",
  "Moongrave Fane",
  "Refabricated",
  "Shield of Senchal",
  "New Moon Priest",
  "Icereach Coven",
  "Pyre Watch",
  "Blackreach Vanguard",
  "Greymoor",
  "Sea Giant",
  "Ancestral Nord",
  "Ancestral Orc",
  "Ancestral High Elf",
  "Thorn Legion",
  "Hazardous Alchemy",
  "Ancestral Akaviri",
  "Ancestral Breton",
  "Ancestral Reach",
  "Nighthollow",
  "Arkthzand Armory",
  "Wayward Guardian",
  "House Hexos",
  "Waking Flame",
  "TrueSworn",
  "Ivory Brigade",
  "SulXan",
  "Black Fin Legion",
  "Ancient Daedric",
  "Crimson Oath",
  "Silver Rose",
  "Annihilarchs Chosen",
  "Fargrave Guardian",
  "Dreadsails",
  "Ascendant Order",
  "Syrbanic Marine",
  "Steadfast Society",
  "Systres Guardian",
];
